:construction: Changed some settings and keybindings in the personal config

diff --git a/scripts/st-copyoutput b/scripts/st-copyoutput
--- a/scripts/st-copyoutput
+++ b/scripts/st-copyoutput
@@ -17,7 +17,10 @@ chosen="$(grep -F "$ps1" "$tmpfile" | sed '$ d' | tac | rofi -theme "$HOME/.conf
 
 eps1="$(echo "$ps1" | sed 's/[^^]/[&]/g; s/\^/\\^/g')"
 
-to_copy="$(awk "/^$chosen$/{p=1;print;next} p&&/$eps1/{p=0};p" "$tmpfile" | head -n -"$(($2 - 1))")"
-
-# copy it to the clipboard
-echo "$to_copy" | xclip -selection clipboard
+while getopts "hn" o; do
+	case "${o}" in
+		h) printf 'Required arguments for custom use:\n  -n: number of line of your prompt\n  -h: Show this message\n' && exit 1 ;;
+		n) echo "$(awk "/^$chosen$/{p=1;print;next} p&&/$eps1/{p=0};p" "$tmpfile" | head -n -"$(($2 - 1))")" | xclip -selection clipboard
+		*) printf 'Invalid option: -%s\n' "$o" && exit 1 ;;
+	esac
+done
diff --git a/scripts/st-urlhandler b/scripts/st-urlhandler
--- a/scripts/st-urlhandler
+++ b/scripts/st-urlhandler
@@ -11,10 +11,10 @@ urls="$(echo "$urls" | sed 's/\(\.\|,\|;\|\!\\|\?\)$//; s/^www./http:\/\/www\./'
 
 [ -z "$urls" ] && exit 1
 
-while getopts "hoc" o; do
+while getopts "hc" o; do
 	case "${o}" in
-		h) printf 'Optional arguments for custom use:\n  -c: copy\n  -o: xdg-open\n  -h: Show this message\n' && exit 1 ;;
+		h) printf 'Optional arguments for custom use:\n  -c: copy\n  -h: Show this message\n' && exit 1 ;;
 		c) echo "$urls" | rofi -theme "$HOME/.config/rofi/themes/with-prompt.rasi" -dmenu -i -p "Copy which url?" | tr -d '\n' | xclip -selection clipboard ;;
-		*) printf 'Invalid option: -%s\n' "$OPTARG" && exit 1 ;;
+		*) printf 'Invalid option: -%s\n' "$o" && exit 1 ;;
 	esac
 done
